### ISSUE TITLE
Application crashes with broken pipe

### ISSUE THREAD

**Issue by Evesy** [alex-leonhardt/sensu-grid#4]
Hi, I recently moved from running Sensu Grid on my local machine to on a virtual server. It's running in a python virtual environment but is crashing soon after starting (lasts around 5 minutes)

`Jul 19 15:10:29 python: Exception in thread Thread-1:`
`Jul 19 15:10:29 python: Traceback (most recent call last):`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner`
`Jul 19 15:10:29 python: self.run()`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/threading.py", line 766, in run`
`Jul 19 15:10:29 python: self.__target(*self.__args, **self.__kwargs)`
`Jul 19 15:10:29 python: File "/usr/local/sensu_grid/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner`
`Jul 19 15:10:29 python: srv.serve_forever()`
`Jul 19 15:10:29 python: File "/usr/local/sensu_grid/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever`
`Jul 19 15:10:29 python: HTTPServer.serve_forever(self)`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 238, in serve_forever`
`Jul 19 15:10:29 python: self._handle_request_noblock()`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 297, in _handle_request_noblock`
`Jul 19 15:10:29 python: self.handle_error(request, client_address)`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock`
`Jul 19 15:10:29 python: self.process_request(request, client_address)`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 321, in process_request`
`Jul 19 15:10:29 python: self.finish_request(request, client_address)`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request`
`Jul 19 15:10:29 python: self.RequestHandlerClass(request, client_address, self)`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 651, in __init__`
`Jul 19 15:10:29 python: self.handle()`
`Jul 19 15:10:29 python: File "/usr/local/sensu_grid/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle`
`Jul 19 15:10:29 python: rv = BaseHTTPRequestHandler.handle(self)`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle`
`Jul 19 15:10:29 python: self.handle_one_request()`
`Jul 19 15:10:29 python: File "/usr/local/sensu_grid/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request`
`Jul 19 15:10:29 python: return self.run_wsgi()`
`Jul 19 15:10:29 python: File "/usr/local/sensu_grid/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi`
`Jul 19 15:10:29 python: execute(self.server.app)`
`Jul 19 15:10:29 python: File "/usr/local/sensu_grid/lib/python2.7/site-packages/werkzeug/serving.py", line 184, in execute`
`Jul 19 15:10:29 python: write(data)`
`Jul 19 15:10:29 python: File "/usr/local/sensu_grid/lib/python2.7/site-packages/werkzeug/serving.py", line 152, in write`
`Jul 19 15:10:29 python: self.send_header(key, value)`
`Jul 19 15:10:29 python: File "/opt/rh/python27/root/usr/lib64/python2.7/BaseHTTPServer.py", line 401, in send_header`
`Jul 19 15:10:29 python: self.wfile.write("%s: %s\r\n" % (keyword, value))`
`Jul 19 15:10:29 python: IOError: [Errno 32] Broken pipe`

I can't claim to know much about Python so I'm not sure where to start with this issue

Cheers

**Comment by Evesy** [comment]
It looks like this is being caused by a health check being performed by the Consul agent on the server. It just does a GET request on the following URL which seems to be triggering the issue: http://localhost:5000

Having temporarily disabled the agent the app was stable overnight and this morning. Interesting to see why this is happening.

**Comment by alex-leonhardt** [comment]
Hi,

thanks for that - would it be possible to get some debug output from consul itself on what the request looks like, is it a actual GET or a HEAD request, etc. ? Does the app break as soon as consul starts checking it, or does it run for a while and then stops? 

I will try and replicate the issue, any info in terms of setup etc you can give would be great! If you could share the consul config, that'd help a lot too.

Thanks!
Alex

**Comment by Evesy** [comment]
Hi Alex,

Thanks for the fast response. The debug information isn't too useful from Consul however I've pasted in some snippets below. The request is a full GET on that URL (When the test is passing you can see the entire body of the response). It doesn't break immediately, typically runs for 2 - 10 minutes before it crashes (Possibly worth noting that the instance that contains 4 DC's died much sooner than an instance that just has one DC configured)

**Consul log**
`2016/07/20 13:04:18 [DEBUG] agent: check 'service:sensu-grid' is passing`
`2016/07/20 13:04:29 [WARN] agent: http request failed 'http://localhost:5000': Get http://localhost:5000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`
`2016/07/20 13:04:29 [DEBUG] agent: Service 'sensu-grid' in sync`
`2016/07/20 13:04:29 [INFO] agent: Synced check 'service:sensu-grid'`
`2016/07/20 13:04:34 [DEBUG] memberlist: Initiating push/pull sync with: 172.28.192.252:8301`
`2016/07/20 13:04:40 [WARN] agent: http request failed 'http://localhost:5000': Get http://localhost:5000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Consul Health Check status** Passing & Failing

Pass:
`HTTP GET http://localhost:5000: 200 OK Output: <!DOCTYPE html>`

Fail:
`Get http://localhost:5000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Consul service check config**
```json
{
  "service": {
    "name": "sensu-grid",
    "tags": null,
    "port": 5000,
    "check": {
      "id": "Web interface",
      "name": "Web interface on port 5000",
      "http": "http://localhost:5000",
      "interval": "10s",
      "timeout": "1s"
    }
  }
}
```

**Sensu grid startup command**
`/usr/local/sensu_grid/bin/python /usr/local/sensu_grid/sensugrid.py`

If there's any other information you feel could be useful let me know

Cheers,
Mike

**Comment by Evesy** [comment]
Forgot to mention that they do state on [their site](https://www.consul.io/docs/agent/checks.html) that the HTTP check output is limited to ~4K so potentially the connection is being prematurely closed by Consul as soon as it has received this amount and Sensu Grid isn't handling it correctly?

**Comment by alex-leonhardt** [comment]
Thanks Mike! I'll have a go at debugging this over the weekend.
Cheers,
Alex

**Comment by alex-leonhardt** [comment]
Hi,

I've been trying to re-produce the error but no success, I'm running this on centos 7 and I tried the built-in dev server as well as gunicorn and both are still running OK (with 4 DCs) after more than 30 minutes.

Could you let me know what OS, config, python, etc. you're using ? From above, I can guess you're using centos or redhat 6 with SCL enabled ?

FWIW - I've tested this on centos7 without SCL using
```
[root@localhost log]# python --version
Python 2.7.5
```

the output so far has been 
```
==> sensu-grid.log <==
127.0.0.1 - - [24/Jul/2016:21:32:09 +0000] "GET / HTTP/1.1" 200 17791 "-" "Consul Health Check"

==> consul_agent.log <==
    2016/07/24 21:32:09 [DEBUG] agent: check 'service:sensu-grid' is passing

==> sensu-grid.log <==
127.0.0.1 - - [24/Jul/2016:21:32:19 +0000] "GET / HTTP/1.1" 200 17791 "-" "Consul Health Check"

==> consul_agent.log <==
    2016/07/24 21:32:19 [DEBUG] agent: check 'service:sensu-grid' is passing
    2016/07/24 21:32:21 [DEBUG] agent: skipping coordinate updates until servers are upgraded
    2016/07/24 21:32:29 [ERR] agent: failed to sync remote state: No known Consul servers

==> sensu-grid.log <==
127.0.0.1 - - [24/Jul/2016:21:32:29 +0000] "GET / HTTP/1.1" 200 17791 "-" "Consul Health Check"

==> consul_agent.log <==
    2016/07/24 21:32:29 [DEBUG] agent: check 'service:sensu-grid' is passing
    2016/07/24 21:32:39 [DEBUG] agent: skipping coordinate updates until servers are upgraded


[snip]


==> sensu-grid.log <==
127.0.0.1 - - [24/Jul/2016:22:02:27 +0000] "GET / HTTP/1.1" 200 17791 "-" "Consul Health Check"

==> consul_agent.log <==
    2016/07/24 22:02:27 [DEBUG] agent: check 'service:sensu-grid' is passing
    2016/07/24 22:02:30 [ERR] agent: failed to sync remote state: No known Consul servers

==> sensu-grid.log <==
127.0.0.1 - - [24/Jul/2016:22:02:38 +0000] "GET / HTTP/1.1" 200 17791 "-" "Consul Health Check"

==> consul_agent.log <==
    2016/07/24 22:02:38 [DEBUG] agent: check 'service:sensu-grid' is passing
    2016/07/24 22:02:38 [DEBUG] agent: skipping coordinate updates until servers are upgraded
    2016/07/24 22:02:45 [ERR] agent: failed to sync remote state: No known Consul servers

==> sensu-grid.log <==
127.0.0.1 - - [24/Jul/2016:22:02:48 +0000] "GET / HTTP/1.1" 200 17791 "-" "Consul Health Check"

==> consul_agent.log <==
    2016/07/24 22:02:48 [DEBUG] agent: check 'service:sensu-grid' is passing
    2016/07/24 22:02:57 [DEBUG] agent: skipping coordinate updates until servers are upgraded

==> sensu-grid.log <==
127.0.0.1 - - [24/Jul/2016:22:02:58 +0000] "GET / HTTP/1.1" 200 17791 "-" "Consul Health Check"

==> consul_agent.log <==
    2016/07/24 22:02:58 [DEBUG] agent: check 'service:sensu-grid' is passing

==> sensu-grid.log <==
10.0.2.2 - - [24/Jul/2016:22:03:02 +0000] "GET / HTTP/1.1" 200 17791 "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

==> consul_agent.log <==
    2016/07/24 22:03:02 [ERR] agent: failed to sync remote state: No known Consul servers

==> sensu-grid.log <==
10.0.2.2 - - [24/Jul/2016:22:03:02 +0000] "GET /static/css/bootstrap-theme.min.css HTTP/1.1" 304 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
10.0.2.2 - - [24/Jul/2016:22:03:02 +0000] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
10.0.2.2 - - [24/Jul/2016:22:03:02 +0000] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
10.0.2.2 - - [24/Jul/2016:22:03:02 +0000] "GET /static/css/adminlte.css HTTP/1.1" 304 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
10.0.2.2 - - [24/Jul/2016:22:03:02 +0000] "GET /static/css/_all-skins.min.css HTTP/1.1" 304 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
10.0.2.2 - - [24/Jul/2016:22:03:02 +0000] "GET /static/js/jquery.min.js HTTP/1.1" 304 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
10.0.2.2 - - [24/Jul/2016:22:03:02 +0000] "GET /static/js/adminlte.min.js HTTP/1.1" 304 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
10.0.2.2 - - [24/Jul/2016:22:03:02 +0000] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
10.0.2.2 - - [24/Jul/2016:22:03:03 +0000] "GET /static/favicon.ico HTTP/1.1" 200 - "http://localhost:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [24/Jul/2016:22:03:08 +0000] "GET / HTTP/1.1" 200 17791 "-" "Consul Health Check"

==> consul_agent.log <==
    2016/07/24 22:03:08 [DEBUG] agent: check 'service:sensu-grid' is passing
```

i've used the latest consul 
```
consul --version
Consul v0.6.4
Consul Protocol: 3 (Understands back to: 1)
```

pip freeze from my virtualenv comes back with
```
(t)[root@localhost log]# pip freeze
Flask==0.11.1
Jinja2==2.8
MarkupSafe==0.23
PyYAML==3.11
Werkzeug==0.11.10
argparse==1.4.0
click==6.6
gunicorn==19.6.0
itsdangerous==0.24
requests==2.10.0
wsgiref==0.1.2
```

I modified the supervisord to use my custom virtualenv
```
[program:sensu-grid]
command=/vagrant/t/bin/gunicorn -n sensu-grid --workers 3 --bind 0.0.0.0:5000 --chdir /opt/sensu-grid --reload --log-file /var/log/sensu-grid.log --access-logfile /var/log/sensu-grid.log --error-logfile /var/log/sensu-grid.log sensugrid:app
priority=999                ; the relative start priority (default 999)
autostart=true              ; start at supervisord start (default: true)
autorestart=true            ; retstart at unexpected quit (default: true)
startsecs=10                ; number of secs prog must stay running (def. 10)
startretries=3              ; max # of serial start failures (default 3)
;exitcodes=0,2               ; 'expected' exit codes for process (default 0,2)
stopsignal=QUIT             ; signal used to kill process (default TERM)
stopwaitsecs=10             ; max num secs to wait before SIGKILL (default 10)
user=sensu-grid                 ; setuid to this UNIX account to run the program
log_stdout=true             ; if true, log program stdout (default true)
log_stderr=true             ; if true, log program stderr (def false)
logfile=/var/log/sensu-grid.log    ; child log path, use NONE for none; default AUTO
logfile_maxbytes=1000MB        ; max # logfile bytes b4 rotation (default 50MB)
logfile_backups=3          ; # of logfile backups (default 10)
```

OOI - how many DCs and checks do you currently have ? It may have something to do with the response size, but that might be then actually be a gunicorn thing (which actually runs the http server) - maybe try running sensu via the built-in dev server and let the checks run against it, does it still die ? 

Also please double-check the versions of python and python modules installed - there might be some weird incompatibility (?) ... 

Hope this helps a little for now, let me know how you get on!

Alex

**Comment by Evesy** [comment]
Hi Alex,

Thanks again for taking a look at this. The machine(s) in question are running CentOS 7.2 with SCL disabled. I've been using the poise python chef cookbook to install Python & all of Sensu Grids requirements.

**Python:**
```
[root@VM-57e46770-c443-4d62-8c6d-fc4f924a1e84 ~]# python --version
Python 2.7.5
[root@VM-57e46770-c443-4d62-8c6d-fc4f924a1e84 ~]# /usr/local/sensu_grid/bin/python --version
Python 2.7.5
```

**Python packages:**
```
[root@VM-57e46770-c443-4d62-8c6d-fc4f924a1e84 ~]# /usr/local/sensu_grid/bin/pip freeze
click==6.6
Flask==0.11.1
gunicorn==19.6.0
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
PyYAML==3.11
requests==2.10.0
Werkzeug==0.11.10
```

**Consul:**
```
[root@VM-57e46770-c443-4d62-8c6d-fc4f924a1e84 ~]# consul --version
Consul v0.6.0
Consul Protocol: 3 (Understands back to: 1)
```

In terms of number of checks/DC's our Sensu Grid that points to Staging is just one DC with about 130 checks, the production Sensu Grid has 4 DC's each of which has an average of 250 checks, however both apps do suffer the same issue.

When I submitted this original issue I was actually just using the dev server (I think), Sensu Grid was simply spawned using a systemd resource that ran:
`/usr/local/sensu_grid/bin/python /usr/local/sensu_grid/sensugrid.py`
I have changed this now to run via gunicorn (although not using supervisord or upstart), just another systemd resource that runs:
`/usr/local/sensu_grid/bin/gunicorn -n sensu-grid --workers 3 --bind 0.0.0.0:5000 --chdir #{node['atchef_sensu_grid']['install_dir']} --reload --log-file /var/log/sensu-grid.log --access-logfile /var/log/sensu-grid.log --error-logfile /var/log/sensu-grid.log sensugrid:app`

Interestingly since making this change the app no longer suffers the original crash that seems to cause the service to just completely hang and stop accepting connections (Hooray!). It has introduced some other slight weirdness though with Consul in that the health check will still intermittently fail despite the application being up and responsive -- The subsequent test will often then pass. I did think this might have been due to the fairly strict one second timeout however increasing this hasn't really affected this. Some log snippets are below:

```
==> sensu-grid.log <==
172.30.151.53 - - [26/Jul/2016:19:27:23 +0000] "GET / HTTP/1.1" 200 8559 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:24 +0000] "GET /static/css/bootstrap-theme.min.css HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chro
me/51.0.2704.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:24 +0000] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/
51.0.2704.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:24 +0000] "GET /static/css/_all-skins.min.css HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51
.0.2704.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:24 +0000] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.
0.2704.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:24 +0000] "GET /static/css/adminlte.css HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.270
4.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:24 +0000] "GET /static/js/adminlte.min.js HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2
704.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:24 +0000] "GET /static/js/jquery.min.js HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.270
4.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:24 +0000] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.
2704.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:24 +0000] "GET /static/fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/static/css/font-awesome.min.css" "Mozilla/5.0 (Windows NT 6.3; WOW64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
172.30.151.53 - - [26/Jul/2016:19:27:25 +0000] "GET /static/favicon.ico HTTP/1.1" 200 - "http://sensu-grid-staging.service.dc1.consul:5000/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103
 Safari/537.36"
127.0.0.1 - - [26/Jul/2016:19:27:48 +0000] "GET / HTTP/1.1" 200 8559 "-" "Consul Health Check"
127.0.0.1 - - [26/Jul/2016:19:27:58 +0000] "GET / HTTP/1.1" 200 8559 "-" "Consul Health Check"

==> consul.log <==
2016/07/26 19:27:38 [WARN] agent: http request failed 'http://localhost:5000': Get http://localhost:5000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2016/07/26 19:27:38 [INFO] agent: Synced check 'service:sensu-grid-staging'
2016/07/26 19:27:48 [INFO] agent: Synced check 'service:sensu-grid-staging'

==> sensu_grid.log <==
127.0.0.1 - - [26/Jul/2016:19:28:29 +0000] "GET / HTTP/1.1" 200 8559 "-" "Consul Health Check"
127.0.0.1 - - [26/Jul/2016:19:28:39 +0000] "GET / HTTP/1.1" 200 8559 "-" "Consul Health Check"
127.0.0.1 - - [26/Jul/2016:19:28:49 +0000] "GET / HTTP/1.1" 200 8559 "-" "Consul Health Check"
127.0.0.1 - - [26/Jul/2016:19:29:14 +0000] "GET / HTTP/1.1" 200 8559 "-" "Consul Health Check"
127.0.0.1 - - [26/Jul/2016:19:29:24 +0000] "GET / HTTP/1.1" 200 8559 "-" "Consul Health Check"
==> consul.log<==
2016/07/26 19:29:04 [WARN] agent: http request failed 'http://localhost:5000': Get http://localhost:5000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2016/07/26 19:29:04 [INFO] agent: Synced check 'service:sensu-grid-staging'2016/07/26 19:29:14 [INFO] agent: Synced check 'service:sensu-grid-staging'
```

I've looked through the Consul changelog and there isn't any immediate bug fixes in the recent versions between what I have and what you're using that might point to this issue. I'll continue to tweak things to see if I can nail down what's causing the issue however I appreciate that it may not be the best use of your time trying to nitpick into this issue but I am thankful for the work you've put in.

As I do have a workaround in the form of using a different method of checking via Consul I'm fairly happy to workaround this issue if it's going to be very difficult to diagnose (which it seems to be!)
Although as a potential feature request it would be cool if Sensu Grid came with a health endpoint that could be hit to quickly check the status of the app (A simple 200 response for example... although I guess I could just do a HEAD request on the app itself which would serve the same purpose)

Thanks again for your help,
Mike

**Comment by alex-leonhardt** [comment]
Hi Mike,

I've downloaded the same consul version and am re-trying to re-create the issue; could you send me the systemd unit file so I can run exactly the same ?

So far I've not had much luck re-producing this; in general though, in production one should probably run the app via   

nginx (deal with http requests, etc.) => (forwards to) gunicorn (spawns X number of) => app (serves the request)  

this way you could even implement a small cache on the nginx layer to not hit the api on every reload necessarily (i'll be working on a in-app cache soon).. 

in terms of feature request, I was thinking the same when I saw this :) ... so that's a 👍 and i'll see if I can put that in relatively quickly (should be easy enough) 

anyway, i'll let you know if i was successful re-producing the issue and when the /healthcheck endpoint is available 

cheers!
alex

**Comment by alex-leonhardt** [comment]
actually, I totally forgot, there already is a 

```
/healthcheck
```

endpoint :) ... can you try that ? 

thanks!
alex

**Comment by Evesy** [comment]
Hi Alex,

The systemd unit file is below (I do need to change the user it runs as at some point!):

```
[Unit]
Description=Starts Sensu Grid

[Install]
WantedBy=multi-user.target

[Service]
ExecStart=/usr/local/sensu_grid/bin/gunicorn -n sensu-grid --workers 3 --bind 0.0.0.0:5000 --chdir /usr/local/sensu_grid --reload --log-file /var/log/sensu-grid.log --access-logfile /var/log/sensu-grid.log --error-logfile /var/log/sensu-grid.log sensugrid:app
Type=simple
User=root
Group=root
```

The consul healthcheck is currently running every 20 seconds with a timeout set to 5 seconds. I did wonder if it's potentially the Sensu API being slow to return however I've not experienced the same in my browser and I haven't observed anything in the Sensu logs either (Will Grid timeout the request after a certain period if the API does not respond?). 

Something like nginx or apache might be something to consider further down the line but right now the dashboard is only requested by one wallboard and the consul healthchecks so it shouldn't be touching the sides at the moment.

I've just reverted my setup in one environment to match how I had it when I was experiencing the original crash and annoyingly I can't seem to get it to crash again (I wanted to see what the healthcheck endpoint looked like when the rest of the application was a bit goosed, to make sure it wouldn't say everything was still OK).

The health check endpoint is pretty much exactly what I was after so I'll change that to be the new URL for the Consul check and let you know if I have any issues with it.

Again, thanks for looking into this

Cheers,
Mike

**Comment by alex-leonhardt** [comment]
Hi Mike, I'll close this if that's ok? Please re-open if you still have issues though!

**Comment by vhosakot** [comment]
I saw this error too in an Ubuntu Docker container on Kubernetes on Ubuntu VM:
```
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
```
I created a brand new Ubuntu xenial VM and ran the same code in Ubuntu Docker container on Kubernetes, and this error was not seen and Python Flask worked as expected. I think it was issue with my host (Ubuntu VM).
