### ISSUE TITLE
Silenced checks do not show as acknowledged

### ISSUE THREAD

**Issue by Evesy** [alex-leonhardt/sensu-grid#6]
In Sensu 0.26 the Silencing feature was overhauled to no longer use Stashes, as such when failing checks are now silenced within Sensu they are not appearing as acknowledged within Grid.

Silenced checks are now accessed via the /silenced API endpoint, example output below:

```
[
  {
    "id": "client:nonprodrabbit4:*",
    "subscription": "client:nonprodrabbit4",
    "check": null,
    "reason": null,
    "creator": "admin",
    "expire_on_resolve": true,
    "expire": 3272
  }
]
```

Would it please be possible to update Grid to look at this new endpoint so that it supports Sensu 0.26?

Cheers

**Comment by thomasriley** [comment]
+1

I would like this update too please. 

Thanks,
Tom

**Comment by alex-leonhardt** [comment]
hi guys, had a quick look and the changes weren't too much work to get this working.

I'll close this now but please do re-open if you think there's something else still not quite working right with the ACK count.

Thanks for bringing this up!
Alex
