### ISSUE TITLE
Update documentation for installation without docker.

### ISSUE THREAD

**Issue by dakar303** [alex-leonhardt/sensu-grid#7]
The documentation is a little confusing when it comes to installing sensu-grid without docker. Specifically,  Is virtualenv something extra that needs to be downloaded? It does not appear to be apart of this repo. 

Thanks!

**Comment by alex-leonhardt** [comment]
Hi, sorry, but I believe that the instructions given so far are sufficient. You can always open a pull request to update the documentation and I can review; I'd have expected that ```virtualenv``` is a python tool known well-enough that it doesn't need explaining. 
Alex
